import { Article } from "./Article.module"


export const ARTICLES : Article []=[
   {id: 1,
   img:'assets/photoArticle.png',
    title: "Les Polymères",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 2,
      img:'assets/science.png',
    title: "Particules",
    author: "Marc MARC", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 3,
      img:'assets/article3.png',
    title: "La Science",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 4,
      img:'assets/article4.png',
    title: "Science",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 5,
      img:'assets/article5.png',
    title: "Elements",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 6,
      img:'assets/article6.png',
    title: "Analyse Thérmique",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 7,
      img:'assets/article7.png',
    title: "Verres",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 8,
      img:'assets/article8.png',
    title: "Chromatographie",
    author: "Jean CLAUD", 
    publicationDate: new Date(25/10/1999),
   },
   {id: 9,
      img:'assets/article9.png',
      title: "Plastiques",
      author: "Jean CLAUD", 
      publicationDate: new Date(25/10/1999),
     }
]